routes:
  - route: "^.+\\.(js|css|svg|ttf)$"
    headers:
      Cache-Control: "max-age=600, no-transform, public"
    gzip: true
  - route: "^.+\\.(png|jpg)$"
    headers:
      Cache-Control: "max-age=600, no-transform, public"
    gzip: false
  - route: "^.+\\.(xml|json)$"
    headers:
      Cache-Control: "max-age=600, no-transform, public"
    gzip: true
  - route: "^.+\\.(html)$"
    headers:
      Cache-Control: "public, max-age=0, must-revalidate"
    gzip: true
